# Initial demo basic pipeline

parameters:
- name: poolName
  type: string
  default: ''
- name: poolDemands
  type: string
  default: ''
- name: mavenSettingsFile
  type: string
  default: ''
- name: artifactsServiceName
  type: string
  default: ''

stages:
  - template: /stages/stage-maven-build.yml
    parameters:
      poolName: ${{ parameters.poolName }}
      poolDemands: ${{ parameters.poolDemands }}
      mavenSettingsFile: ${{ parameters.mavenSettingsFile }}
      artifactsServiceName: ${{ parameters.artifactServiceName }}