# Initial demo basic pipeline

parameters:
- name: poolName
  type: string
  default: ''
- name: poolDemands
  type: string
  default: ''
- name: mavenSettingsFile
  type: string
  default: ''
- name: artifactServiceName
  type: string
  default: ''

stages:
  - template: /stages/stage-maven-build.yml
    parameters:
      poolName: ${{ parameters.poolName }}
      poolDemands: ${{ parameters.poolDemands }}
      mavenSettingsFile: ${{ parameters.mavenSettingsFile }}
      artifactServiceName: ${{ parameters.artifactServiceName }}
  - template: /stages/stage-maven-publish.yml
    parameters:
      poolName: ${{ parameters.poolName }}  
      poolDemands: ${{ parameters.poolDemands }}      
      mavenSettingsFile: ${{ parameters.mavenSettingsFile }}
      artifactServiceName: ${{ parameters.artifactServiceName }}
