# SonarCloud scan for maven artifact

parameters:
- name: stageDependsOn
  type: string
  default: 'build_and_test_maven_artifacts'
- name: poolName
  type: string
  default: ''
- name: poolDemands
  type: string
  default: ''

stages:  
  - stage: 'sonar_scan_maven_artifacts'
    dependsOn: ${{ parameters.stageDependsOn }}
    displayName: 'Sonar: Scan artifacts'
    jobs:
    - job: sonar_scan_artifacts
      pool:
        name: ${{ parameters.poolName }}       
        demands: 
        - ${{ parameters.poolDemands }}
      steps:
      - task: SonarCloudPrepare@1
        displayName: 'Prepare SonarCloud analysis'
        inputs:
          SonarCloud: 'SonarCloud-CodeAnalysis-Server'
          organization: az-pipelines-sonarcloud-org
          projectKey: 'bdc33ef3e89853f175f5c3540aa8c5839f6e016f'
          projectName: 'az-pipelines-1'
      - task: SonarCloudAnalyze@1
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'