# Stage for building and testing maven artifacts

parameters:
- name: stageDependsOn
  type: string
  default: ''
- name: poolName
  type: string
  default: ''
- name: poolDemands
  type: string
  default: ''
- name: mavenSettingsFile
  type: string
  default: ''
- name: artifactsServiceName
  type: string
  default: ''
- name: mavenOpts
  type: string
  default: ''

stages:
  - stage: 'build_and_test_maven_artifacts'
    dependsOn: ${{ parameters.stageDependsOn }}
    displayName: 'Maven: Build and test artifacts'
    jobs:
    - job: maven_build_and_test
      pool:
        name: ${{ parameters.poolName }}
        demands:
        - ${{ parameters.poolDemands }}
      steps:
      - task: DownloadSecureFile@1
        name: m2Settings
        displayName: 'Download maven settings.xml'
        inputs:
          secureFile: '${{ parameters.mavenSettingsFile }}'
      - bash: |
          mkdir ${HOME}/.m2
          cp $(m2Settings.secureFilePath) ${HOME}/.m2/settings.xml
        displayName: 'Move settings to .m2 folder'
      - task: MavenAuthenticate@0
        displayName: 'Maven Authenticate'
        inputs:
          MavenServiceConnections: ${{ parameters.artifactsServiceName }}
      - task: Maven@3
        displayName: Maven build.
        inputs:
          mavenPomFile: 'pom.xml'
          goals: clean compile
          mavenOptions: -Dmaven.repo.local=$(Build.SourcesDirectory)/m2-repository ${{ parameters.mavenOpts }}
          options: -U -B
          publishJUnitResults: false      
      - task: Maven@3
        displayName: Maven test and verify.
        inputs:
          mavenPomFile: 'pom.xml'
          goals: test verify
          mavenOptions: -Dmaven.repo.local=$(Build.SourcesDirectory)/m2-repository ${{ parameters.mavenOpts }}
          options: -U -B
